### PR TITLE
Improvements, do some TODOs, fix rainbow.cr

### PR DESCRIPTION
**Pull request by r00ster91**
This
* Makes the specs run again by updating the [minitest](https://github.com/ysbaddaden/minitest.cr) version
* Fixes the example in [examples/rainbow.cr](https://github.com/stumpycr/stumpy_png/blob/master/examples/rainbow.cr) (right now there are some [wrong pixels at the edge of the image](https://raw.githubusercontent.com/stumpycr/stumpy_png/master/examples/rainbow.png))
* Uses more `Tuple`s instead of `Array`s which is probably a bit faster.
* Fixes 3 **TODO**s by using IO::ByteFormat::BigEndian.encode

### CODE REVIEW

**Comment by l3kn** [comment]
Great, thanks!

**Comment by Michionlion** [comment]
I'm not sure if this broke something or I'm doing something wrong, but after `4.4.0` something is seriously wrong with 8 bit output. I'm getting completely different output when drawing basic shapes -- it seems that something has changed or was broken with the encoding. I've included a spec below. Just include that in a project and switch versions from 4.3 to 4.4, as well as changing the big_depth saved at.

```
require "stumpy_png"
require "spec"

class Graphic
  include StumpyPNG

  enum MixMode
    Linear
    Alpha
    Multiply
    None
  end

  getter canvas : Canvas

  getter color : RGBA = RGBA::WHITE
  property mixing : MixMode = MixMode::Alpha

  getter size : Tuple(Float64, Float64)

  def initialize(@size)
    @canvas = Canvas.new size[0].round.to_i, size[1].round.to_i, RGBA.from_hex("#00000000")
  end

  def color=(new_color : RGBA)
    @color = new_color
  end

  # Naive circle drawing algorithm
  def circle(x : Number, y : Number, radius : Number)
    start_x = (x - radius).floor.to_i
    end_x = (x + radius).ceil.to_i
    start_y = (y - radius).floor.to_i
    end_y = (y + radius).ceil.to_i

    (start_x..end_x).each do |cx|
      (start_y..end_y).each do |cy|
        fill cx, cy if (cx - start_x - radius.ceil.to_i)**2 + (cy - start_y - radius.ceil.to_i)**2 <= radius**2 * 0.8
      end
    end
  end

  def fill(x, y, with new_color = color)
    # puts "safe pixel at #{x}, #{y}"
    mixed = mix new_color, x, y
    canvas.safe_set x, y, mixed
  end

  private def mix(new_color, x, y, keep_old_percent = 0.5)
    return new_color if canvas.safe_get(x, y).nil?

    case mixing
    when MixMode::Alpha    then new_color.over canvas.safe_get(x, y).as(RGBA)
    when MixMode::Linear   then new_color.mix canvas.safe_get(x, y).as(RGBA), keep_old_percent
    when MixMode::Multiply then new_color.multiply canvas.safe_get(x, y).as(RGBA)
    else                        new_color
    end
  end
end



describe "circle test" do
  it "draws a bunch of circles" do
    graphic = Graphic.new({1310.0, 32.0})

    graphic.color = StumpyPNG::RGBA::BLUE

    x = 5
    0.step to: 100 do |radius10|
      radius = radius10 / 10.0
      graphic.circle x.round.to_i, 16, radius
      graphic.fill x.round.to_i, 16, StumpyPNG::RGBA.from_relative(1, 1, 1, 0.4) if radius > 2
      x += radius * 2 + 3
    end

    StumpyPNG.write graphic.canvas, "circle_test.png", bit_depth: 16
  end
end
```

**Comment by asterite** [comment]
Using tuples here is probably slower. The hash ends up being a union of types and accessing each elements involves more computation.

I'll never get tired of saying this: tuples are for returning multiple values from a method. All other usages are smells.

**Comment by asterite** [comment]
Did you benchmark this change?

**Pull request merged**
