### PR TITLE
Fixed for 0.35.0

### PR DESCRIPTION
**Pull request by bararchy**

### CODE REVIEW

**Comment by neutrinog** [comment]
@l3kn putting aside the fact that crystal is still pre `1.0`. I'd suggest ticking with the standard, that is, go ahead and bump to `5.0` since this is a breaking change as I understand it.

**Comment by neutrinog** [comment]
FYI there's some discussion over in this PR https://github.com/schovi/baked_file_system/pull/36 (practically identical to this one) on whether or not returning `slice.size.to_i64` is sufficient.

It might be good to keep an eye on the outcome of that conversation.

**Comment by bararchy** [comment]
@l3kn this PR shouldn't be merged as it seems Crystal is reverting this change.

**Comment by l3kn** [comment]
@bararchy Ok, I'll close this for now.

For further reference:
- https://github.com/crystal-lang/crystal/pull/9469
- https://github.com/crystal-lang/crystal/pull/9233#issuecomment-642726015

**Pull request closed without merging**
